# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t15lBR1Vf-bOEj2gZ2EpXrsSCwAFctSS
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # --- 1. Load the Saved Model ---
# try:
#     model = joblib.load('best_churn_model.pkl')
# except FileNotFoundError:
#     st.error("Error: 'best_churn_model.pkl' not found. Please ensure you saved the model in Colab first!")
#     st.stop()
# 
# # --- 2. Build the Web App UI ---
# st.set_page_config(page_title="Churn Predictor", page_icon="🏦", layout="centered")
# 
# st.title("🏦 Bank Customer Churn Predictor")
# st.write("Enter the customer's details below to predict if they will leave the bank.")
# st.markdown("---")
# 
# # Create two columns for a cleaner layout
# col1, col2 = st.columns(2)
# 
# with col1:
#     st.subheader("Personal Details")
#     Geography = st.selectbox("Geography (Country)", ["France", "Germany", "Spain"])
#     Gender = st.selectbox("Gender", ["Male", "Female"])
#     Age = st.slider("Age", min_value=18, max_value=100, value=35)
#     Tenure = st.slider("Tenure (Years with Bank)", min_value=0, max_value=10, value=5)
#     EstimatedSalary = st.number_input("Estimated Salary ($)", min_value=0.0, value=60000.0, step=1000.0)
# 
# with col2:
#     st.subheader("Account Details")
#     CreditScore = st.number_input("Credit Score", min_value=300, max_value=850, value=650)
#     Balance = st.number_input("Account Balance ($)", min_value=0.0, value=50000.0, step=1000.0)
#     NumOfProducts = st.selectbox("Number of Products", [1, 2, 3, 4])
#     HasCrCard = st.selectbox("Has Credit Card?", ["Yes", "No"])
#     IsActiveMember = st.selectbox("Is Active Member?", ["Yes", "No"])
# 
# st.markdown("---")
# 
# # --- 3. Backend Data Conversion ---
# # Convert Yes/No to 1/0
# has_crcard_encoded = 1 if HasCrCard == "Yes" else 0
# is_active_encoded = 1 if IsActiveMember == "Yes" else 0
# 
# # Convert Gender to 1/0
# # (Assuming Male=1, Female=0 from standard Label Encoding)
# gender_encoded = 1 if Gender == "Male" else 0
# 
# # Convert Geography to numbers
# # (Assuming France=0, Germany=1, Spain=2 from standard Label Encoding)
# geo_dict = {"France": 0, "Germany": 1, "Spain": 2}
# geography_encoded = geo_dict[Geography]
# 
# # --- 4. Make the Prediction ---
# if st.button("Predict Churn Risk", type="primary", use_container_width=True):
# 
#     # Build the DataFrame in the EXACT order your model was trained on
#     input_data = pd.DataFrame({
#         'CreditScore': [CreditScore],
#         'Geography': [geography_encoded],
#         'Gender': [gender_encoded],
#         'Age': [Age],
#         'Tenure': [Tenure],
#         'Balance': [Balance],
#         'NumOfProducts': [NumOfProducts],
#         'HasCrCard': [has_crcard_encoded],
#         'IsActiveMember': [is_active_encoded],
#         'EstimatedSalary': [EstimatedSalary]
#     })
# 
#     # Generate prediction and probability
#     prediction = model.predict(input_data)
#     probability = model.predict_proba(input_data)[0][1] * 100
# 
#     # Display results beautifully
#     st.markdown("### Prediction Results:")
#     if prediction[0] == 1:
#         st.error(f"⚠️ **High Risk of Churn!**")
#         st.write(f"The model predicts a **{probability:.1f}%** probability that this customer will close their accounts.")
#     else:
#         st.success(f"✅ **Safe: Customer is likely to stay.**")
#         st.write(f"The model predicts only a **{probability:.1f}%** probability of churn.")